# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
    ]
