# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161031_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxlog',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Null'), (1, 'Criado'), (2, 'Atualizado'), (3, 'Deletado')], default=0, verbose_name='Status'),
        ),
    ]
