# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_boxlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
