# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161031_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='slug',
        ),
    ]
